[build]
  command = "pip install -r requirements.txt"
  functions = "netlify/functions"
  publish = "."

[build.environment]
  PYTHON_VERSION = "3.10"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/app/:splat"
  status = 200

[functions]
  directory = "netlify/functions"
