services:
  # Web Service
  - type: web
    name: botfactory
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: botfactory-db
          property: connectionString
      - key: GEMINI_API_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
    autoDeploy: true
    
  # PostgreSQL Database
  - type: pgsql
    name: botfactory-db
    plan: free
    databaseName: botfactory
    databaseUser: botfactory_user
